---
name: Deploy docker
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  deploy_docker:
    uses: khanlab/actions/.github/workflows/workflow-release_task-deployDocker.yml@v0.3.4
    with:
      maximize_space: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
